#!/bin/bash
[200~File Edit Options Buffers Tools Sh-Script Help
 #!/bin/bash




















 -UU-:**--F1  0-preprocessor   All L2    Git-main  (Shell-script[bash]) --------------------------------~
